# This config file defines the current topology of the UP1 robot.
# It can be manually edited until there is a better mechanism for module discovery.

# Currently supported modules:
#   base_module:
#     - wheeled_base
#   manipulator_module:
#     - dual_arm
#     - mono_arm
#   io_module:
#     - stereo_cam

up1:
  modules:
    base_module: wheeled_base
    manipulator_module: dual_arm
    io_module: stereo_cam
